# Generated by Django 3.2.7 on 2023-04-07 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(default='New Session', max_length=20, verbose_name='Session name')),
                ('session_descriptions', models.CharField(default='Description', max_length=150, verbose_name='Session descriptions')),
                ('session_ref_number', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Session reference code')),
                ('exam_start', models.DateTimeField(verbose_name='Exam start time')),
                ('strict_timing', models.BooleanField(default=False, verbose_name='Strict Timing')),
                ('show_score', models.BooleanField(default=False, verbose_name='Show scores at the end to the applicant?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active session?')),
                ('session_total_seats', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total number of seats')),
                ('session_occupied_seats', models.PositiveIntegerField(blank=True, default=0, verbose_name='Number of occupied seats')),
                ('course_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_course_exams', to='questions.courseexammodel')),
                ('participants', models.ManyToManyField(related_name='course_exams', to=settings.AUTH_USER_MODEL, verbose_name='Exam participant')),
                ('questions', models.ManyToManyField(to='questions.QuestionModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(default='New Session', max_length=20, verbose_name='Session name')),
                ('session_descriptions', models.CharField(default='Description', max_length=150, verbose_name='Session descriptions')),
                ('session_ref_number', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Session reference code')),
                ('exam_start', models.DateTimeField(verbose_name='Exam start time')),
                ('strict_timing', models.BooleanField(default=False, verbose_name='Strict Timing')),
                ('show_score', models.BooleanField(default=False, verbose_name='Show scores at the end to the applicant?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active session?')),
                ('session_total_seats', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total number of seats')),
                ('session_occupied_seats', models.PositiveIntegerField(blank=True, default=0, verbose_name='Number of occupied seats')),
                ('participants', models.ManyToManyField(related_name='subject_exams', to=settings.AUTH_USER_MODEL, verbose_name='Exam participant')),
                ('questions', models.ManyToManyField(to='questions.QuestionModel')),
                ('subject_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_exam_sessions', to='questions.subjectexammodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_ref_number', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Session reference code')),
                ('exam_start', models.DateTimeField(verbose_name='Exam start time')),
                ('show_score', models.BooleanField(default=False, verbose_name='Show scores at the end to the applicant?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active session?')),
                ('session_total_seats', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total number of seats')),
                ('session_occupied_seats', models.PositiveIntegerField(blank=True, default=0, verbose_name='Number of occupied seats')),
                ('course_sessions', models.ManyToManyField(related_name='subexam_fsessions', to='exam_sessions.CourseExamSession', verbose_name='Included Course Exams')),
                ('subject_sessions', models.ManyToManyField(related_name='subexam_fsessions', to='exam_sessions.SubjectExamSession', verbose_name='Included Subject Exams')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_ref_number', models.CharField(blank=True, max_length=20, verbose_name='Session reference code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField(blank=True, null=True, verbose_name='Answers')),
                ('wrong_answers', models.JSONField(blank=True, null=True, verbose_name='Wrong Answers')),
                ('not_answered', models.JSONField(blank=True, null=True, verbose_name='Not Answered')),
                ('num_wrong', models.IntegerField(blank=True, null=True, verbose_name='Number of wrong answered questions')),
                ('num_not_answered', models.IntegerField(blank=True, null=True, verbose_name='Number of not answered questions')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Score')),
                ('exam_duration', models.IntegerField(blank=True, default=0, verbose_name='Exam duration')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Passed in exam')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Exam is finished')),
                ('show_score', models.BooleanField(default=False, verbose_name='Show score at the end of the exam?')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Exam Results',
                'unique_together': {('student', 'session_ref_number')},
            },
        ),
    ]
