# Generated by Django 3.2.7 on 2021-11-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresults',
            name='exam_duration',
            field=models.IntegerField(blank=True, default=0, verbose_name='Exam duration'),
        ),
        migrations.AddField(
            model_name='examresults',
            name='not_answered',
            field=models.JSONField(blank=True, null=True, verbose_name='Not Answered'),
        ),
        migrations.AddField(
            model_name='examresults',
            name='num_not_answered',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of not answered questions'),
        ),
        migrations.AddField(
            model_name='examresults',
            name='num_wrong',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of wrong answered questions'),
        ),
        migrations.AddField(
            model_name='examresults',
            name='wrong_answers',
            field=models.JSONField(blank=True, null=True, verbose_name='Wrong Answers'),
        ),
    ]
