# Generated by Django 3.2.7 on 2021-11-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresults',
            name='exam_time',
            field=models.IntegerField(blank=True, default=0, verbose_name='Exam duration'),
        ),
    ]
