# Generated by Django 3.2.7 on 2021-09-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexamsession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active session?'),
        ),
        migrations.AddField(
            model_name='examresults',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Exam is finished'),
        ),
        migrations.AddField(
            model_name='subjectexamsession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active session?'),
        ),
    ]
