# Generated by Django 3.2.7 on 2023-03-31 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexamsession',
            name='session_occupied_seats',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Number of occupied seats'),
        ),
        migrations.AddField(
            model_name='courseexamsession',
            name='session_total_seats',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Total number of seats'),
        ),
        migrations.AddField(
            model_name='subjectexamsession',
            name='session_occupied_seats',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Number of occupied seats'),
        ),
        migrations.AddField(
            model_name='subjectexamsession',
            name='session_total_seats',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Total number of seats'),
        ),
        migrations.RemoveField(
            model_name='courseexamsession',
            name='participants',
        ),
        migrations.AddField(
            model_name='courseexamsession',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Exam participant'),
        ),
        migrations.RemoveField(
            model_name='subjectexamsession',
            name='participants',
        ),
        migrations.AddField(
            model_name='subjectexamsession',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Exam participant'),
        ),
    ]
