# Generated by Django 3.2.7 on 2023-04-07 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeexamsession',
            options={'verbose_name': 'Free Exam Session', 'verbose_name_plural': 'Free Exam Sessions'},
        ),
    ]
