# Generated by Django 3.2.7 on 2023-04-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions', '0002_alter_freeexamsession_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseexamsession',
            name='session_occupied_seats',
        ),
        migrations.RemoveField(
            model_name='subjectexamsession',
            name='session_occupied_seats',
        ),
    ]
