# Generated by Django 3.2.7 on 2023-04-03 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam_sessions', '0002_auto_20230331_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexamsession',
            name='participants',
            field=models.ManyToManyField(related_name='course_exams', to=settings.AUTH_USER_MODEL, verbose_name='Exam participant'),
        ),
        migrations.AlterField(
            model_name='subjectexamsession',
            name='participants',
            field=models.ManyToManyField(related_name='subject_exams', to=settings.AUTH_USER_MODEL, verbose_name='Exam participant'),
        ),
    ]
