# Generated by Django 3.2.7 on 2021-10-05 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions', '0003_auto_20210928_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresults',
            name='course_exam_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_session', to='exam_sessions.courseexamsession'),
        ),
    ]
