# Generated by Django 3.2.7 on 2023-04-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions', '0003_auto_20230407_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeexamsession',
            name='course_sessions',
            field=models.ManyToManyField(related_name='course_exam_fsessions', to='exam_sessions.CourseExamSession', verbose_name='Included Course Exams'),
        ),
        migrations.AlterField(
            model_name='freeexamsession',
            name='subject_sessions',
            field=models.ManyToManyField(related_name='sub_exam_fsessions', to='exam_sessions.SubjectExamSession', verbose_name='Included Subject Exams'),
        ),
    ]
