# Generated by Django 3.2.7 on 2021-10-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions', '0004_alter_examresults_course_exam_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresults',
            name='answers',
            field=models.JSONField(null=True, verbose_name='Answers'),
        ),
    ]
