# Generated by Django 3.2.7 on 2021-10-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_sessions', '0005_alter_examresults_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresults',
            name='course_exam_session',
        ),
        migrations.RemoveField(
            model_name='examresults',
            name='subject_exam_session',
        ),
        migrations.AddField(
            model_name='examresults',
            name='session_ref_number',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Session reference code'),
        ),
    ]
