# Generated by Django 3.2.7 on 2021-10-14 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20211007_1219'),
        ('exam_sessions', '0006_auto_20211007_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresults',
            name='session_ref_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Session reference code'),
        ),
        migrations.AlterField(
            model_name='subjectexamsession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_exam_sessions', to='questions.subjectexammodel'),
        ),
    ]
