# Generated by Django 3.2.7 on 2021-10-15 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam_sessions', '0008_rename_subject_subjectexamsession_subject_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresults',
            name='session_ref_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Session reference code'),
        ),
        migrations.AlterUniqueTogether(
            name='examresults',
            unique_together={('student', 'session_ref_number')},
        ),
    ]
