# Generated by Django 3.2.7 on 2024-05-14 07:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Cell Phone Numeber'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path, validators=[users.models.file_size]),
        ),
    ]
