# Generated by Django 3.2.7 on 2021-09-15 14:47

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import questions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='Course name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, verbose_name='Subject')),
                ('instruction_hours', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)], verbose_name='Instruction hours')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='questions.coursemodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('question_content', ckeditor.fields.RichTextField(verbose_name='Question')),
                ('question_ref_code', models.CharField(max_length=10)),
                ('opt_1', ckeditor.fields.RichTextField(verbose_name='A')),
                ('opt_2', ckeditor.fields.RichTextField(verbose_name='B')),
                ('opt_3', ckeditor.fields.RichTextField(verbose_name='C')),
                ('opt_4', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='D')),
                ('question_file', models.FileField(null=True, upload_to=questions.models.question_files, verbose_name='Question supplementary file')),
                ('correct_answer', models.CharField(choices=[('A', '1'), ('B', '2'), ('C', '3'), ('D', '4')], max_length=1, verbose_name='Correct answer')),
                ('difficulty_level', models.CharField(choices=[('Easy', 'easy'), ('Medium', 'medium'), ('Hard', 'hard'), ('Very Hard', 'very hard')], max_length=20, verbose_name='Difficulty Level')),
                ('numb_of_appeared', models.IntegerField(default=0, verbose_name='Number of times the question appeared in exams')),
                ('correctly_answered_times', models.IntegerField(default=0, verbose_name='Number of times the question answered correctly')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
