# Generated by Django 3.2.7 on 2023-04-03 14:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='opt_3',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='C'),
        ),
    ]
