# Generated by Django 3.2.7 on 2021-10-22 19:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='opt_1',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='opt_2',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='B'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='opt_3',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='opt_4',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='question_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Question'),
        ),
    ]
