# Generated by Django 3.2.7 on 2021-09-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='question_ref_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
