# Generated by Django 3.2.7 on 2023-04-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexammodel',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_exam', to='questions.coursemodel'),
        ),
        migrations.AlterField(
            model_name='subjectexammodel',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject_exams', to='questions.subjectmodel'),
        ),
    ]
