# Generated by Django 3.2.7 on 2021-09-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_questionmodel_question_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='question_ref_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
