# Generated by Django 3.2.7 on 2021-10-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20211022_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='correct_answer',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], verbose_name='Correct answer'),
        ),
    ]
