# Generated by Django 3.2.7 on 2024-05-14 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_coursemodel_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmodel',
            name='course',
        ),
        migrations.AddField(
            model_name='courseexammodel',
            name='has_penalty',
            field=models.BooleanField(default=False, verbose_name='Has penalty for wrong answers?'),
        ),
        migrations.AddField(
            model_name='courseexammodel',
            name='penalize_for',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='How many wrong answers penalizes one score?'),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='subjects',
            field=models.ManyToManyField(related_name='sub_courses', to='questions.SubjectModel'),
        ),
        migrations.AddField(
            model_name='subjectexammodel',
            name='has_penalty',
            field=models.BooleanField(default=False, verbose_name='Has penalty for wrong answers?'),
        ),
        migrations.AddField(
            model_name='subjectexammodel',
            name='penalize_for',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='How many wrong answers penalizes one score?'),
        ),
    ]
