# Generated by Django 3.2.7 on 2021-09-15 16:30

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_questionmodel_question_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='correct_answer',
            field=models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, verbose_name='Correct answer'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('very hard', 'Very hard')], max_length=20, verbose_name='Difficulty Level'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to=questions.models.question_files, verbose_name='Question supplementary file'),
        ),
    ]
