# Generated by Django 3.2.7 on 2021-09-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_questionmodel_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='questions.subjectmodel'),
        ),
    ]
