# Generated by Django 3.2.7 on 2021-09-19 13:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_questionmodel_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50, unique=True, verbose_name='Session Name')),
                ('noq_total', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of questions')),
                ('exam_duration', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Exam duration in minutes')),
                ('pass_score', models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('show_score', models.BooleanField(default=False, verbose_name='Show scores at the end to the applicant?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Exam model is active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_exam', to='questions.coursemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=50, unique=True, verbose_name='Session Name')),
                ('noq_total', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of questions')),
                ('exam_duration', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Exam duration in minutes')),
                ('pass_score', models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('show_score', models.BooleanField(default=False, verbose_name='Show scores at the end to the applicant?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Exam model is active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_exams', to='questions.subjectmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerSubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noq_subject', models.IntegerField(help_text="Total number of questions should not exceed exam's number of questions", verbose_name='Number of questions in this subject')),
                ('course_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_for_course', to='questions.courseexammodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_for_exam', to='questions.subjectmodel')),
            ],
        ),
    ]
