# Generated by Django 3.2.7 on 2021-09-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_courseexammodel_persubjectmodel_subjectexammodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseexammodel',
            name='show_score',
        ),
        migrations.RemoveField(
            model_name='subjectexammodel',
            name='show_score',
        ),
        migrations.AlterField(
            model_name='courseexammodel',
            name='exam_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Exam Name'),
        ),
        migrations.AlterField(
            model_name='persubjectmodel',
            name='noq_subject',
            field=models.IntegerField(default=0, help_text="Total number of questions should not exceed exam's number of questions", verbose_name='Number of questions in this subject'),
        ),
        migrations.AlterField(
            model_name='subjectexammodel',
            name='exam_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Exam Name'),
        ),
    ]
