# Generated by Django 3.2.7 on 2021-10-07 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20210919_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseexammodel',
            options={'verbose_name': 'Course based exam'},
        ),
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'verbose_name': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='questionmodel',
            options={'verbose_name': 'Question bank'},
        ),
        migrations.AlterModelOptions(
            name='subjectexammodel',
            options={'verbose_name': 'Subject based exam'},
        ),
        migrations.AlterModelOptions(
            name='subjectmodel',
            options={'verbose_name': 'Subject'},
        ),
    ]
